darwin.apple_sdk.frameworks: add missing dependencies
```
/nix/store/5mgn511gbldf7xl5kjm27z9lj10xcycl-apple-framework-CoreData-11.0.0/Library/Frameworks/CoreData.framework/Headers/NSPersistentCloudKitContainerOptions.h:10:9: fatal error: 'CloudKit/CKDatabase.h' file not found
        ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

```
/nix/store/a7k7kqj08602785vsrss0xa85b08hik4-apple-framework-CloudKit-11.0.0/Library/Frameworks/CloudKit.framework/Headers/CKRecord.h:9:9: fatal error: 'CoreLocation/CLLocation.h' file not found
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```