darwin.file_cmds: add missing Libinfo dependency
Fixing:

```
/private/tmp/nix-build-file_cmds-264.1.1-osx-10.11.6.drv-0/file_cmds-264.1.1/ls/print.c:56:10: fatal error: 'membershipPriv.h' file not found
         ^~~~~~~~~~~~~~~~~~
1 error generated.
```